-- MySQL Script generated by MySQL Workbench
-- Mon Mar 30 01:53:58 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema StudentEnrollmentDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema StudentEnrollmentDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `StudentEnrollmentDB` ;
USE `StudentEnrollmentDB` ;

-- -----------------------------------------------------
-- Table `StudentEnrollmentDB`.`students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `StudentEnrollmentDB`.`students` (
  `idstudent` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(50) NOT NULL,
  `last_name` VARCHAR(50) NOT NULL,
  `age` INT NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idstudent`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `StudentEnrollmentDB`.`courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `StudentEnrollmentDB`.`courses` (
  `course_id` INT NOT NULL AUTO_INCREMENT,
  `course_name` VARCHAR(45) NOT NULL,
  `course_description` VARCHAR(255) NULL,
  `credits` INT NOT NULL,
  PRIMARY KEY (`course_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `StudentEnrollmentDB`.`enrollments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `StudentEnrollmentDB`.`enrollments` (
  `enrollment_id` INT NOT NULL AUTO_INCREMENT,
  `student_id` INT NOT NULL,
  `course_id` INT NOT NULL,
  `enrollment_date` DATETIME NULL,
  PRIMARY KEY (`enrollment_id`),
  INDEX `fk_enrollments_students_idx` (`student_id` ASC) VISIBLE,
  INDEX `fk_enrollments_course_idx` (`course_id` ASC) VISIBLE,
  CONSTRAINT `fk_enrollments_students`
    FOREIGN KEY (`student_id`)
    REFERENCES `StudentEnrollmentDB`.`students` (`idstudent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_enrollments_course`
    FOREIGN KEY (`course_id`)
    REFERENCES `StudentEnrollmentDB`.`courses` (`course_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
